seller item and reviews screen backend integration
map-of-pi/map-of-pi-frontend pull request #118
Opened 2024-07-15 13:05 UTC by adisa39

when run on sandbox:

- New users are automatically signup and returning users are automatically login with the user token stored on localStorage .

- authenticated user can add reply to seller views.

2024-07-16 03:16 UTC, swoocn commented
Hey @adisa39 - 
I can't seem to auto-login nor login with my Pi ID in the sandbox environment.  This is what I am getting ->

![image](https://github.com/user-attachments/assets/077e2e0f-b53d-4aa3-9cdb-ac33a4edeccc)

Please advise when you can.  Thanks!

2024-07-16 05:34 UTC, adisa39 commented
> Hey @adisa39 - I can't seem to auto-login nor login with my Pi ID in the sandbox environment. This is what I am getting ->
> 
> ![image](https://private-user-images.githubusercontent.com/72060658/348925855-077e2e0f-b53d-4aa3-9cdb-ac33a4edeccc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMDgyMzQsIm5iZiI6MTcyMTEwNzkzNCwicGF0aCI6Ii83MjA2MDY1OC8zNDg5MjU4NTUtMDc3ZTJlMGYtYjUzZC00YWEzLTljZGItYWMzM2E0ZWRlY2NjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDA1MzIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYTEyZTVmODkyMTZhOWFlMmI3MTJhNmM1ZTliYzQ5YjBmNDM3YTkxOWZkODkwMTU0ZGViNTQwZGZiMzdlNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iqvxoqyAMH056NDKbG_HQRPgUP1ZBvsf5PU7aTyGIkk)
> 
> Please advise when you can. Thanks!

2024-07-16 05:37 UTC, adisa39 commented
If

2024-07-16 06:22 UTC, adisa39 commented
Hi @swoocn. you should try add a review to seller.
Also Check console for auth credentials or error

2024-07-16 22:10 UTC, swoocn commented
> Hi @swoocn. you should try add a review to seller. Also Check console for auth credentials or error

This is what I am getting @adisa39 ->

![image](https://github.com/user-attachments/assets/12a4e98f-532c-491b-985f-1f0a780665f3)

2024-07-18 02:26 UTC, swoocn commented
Hi @adisa39 - I'm still getting the same error, but I managed to login and authenticate with my Pioneer ID **AFTER** I made some adjustments to the registerUser in the AppContentProvider.tsx ->
`const res = await axiosClient.post("/users/authenticate", { auth: {user} });  `

Note that the request body for the authenticate API operation has an **auth** section per the Swagger Doc ->
![image](https://github.com/user-attachments/assets/b0c5bfb3-238b-4a18-b4e8-17a2a798284f)

I'm quite confused how you are able to get your changes to work in the sandbox environment without it.. 🤔

2024-07-18 02:29 UTC, swoocn commented
Even though I am successfully logged in, I still am unable to add a review ->
![image](https://github.com/user-attachments/assets/a7bba365-1f21-4f5a-93bb-11a7a4abc949)

Can you please look at this some more?  Feel free to reach out if you want to initiate a call/ screen sharing.

2024-07-18 02:30 UTC, swoocn commented on context/AppContextProvider.tsx
> +        const res = await axiosClient.post("/users/authenticate", {user})
I had to change L55 to `const res = await axiosClient.post("/users/authenticate", { auth: {user} }); ` to get the login to work.

2024-07-18 02:31 UTC, swoocn requested changes
Please make sure you unit test the integration.  Thanks!

2024-07-18 02:32 UTC, adisa39 commented
The error was because you not testing with the latest PR with the backend

2024-07-18 12:31 UTC, swoocn commented on src/constants/types.tsx
Hey @omotoshoayomikun - Any chance you could leverage the existing **SellerType** and **ReviewFeedbackType** instead of building new models i.e., CreateSellerType and CreateReviewType?

2024-07-18 12:40 UTC, swoocn commented on src/services/api.ts
> +    return {message: 'Error fetching pioneer user with ID',}
Is there a reason why this error handling was replaced?  Regardless, the return message looks incomplete to me.

2024-07-18 13:01 UTC, adisa39 commented on src/services/api.ts
> +    return {message: 'Error fetching pioneer user with ID',}
Was just trying to trace the error

2024-07-18 13:02 UTC, adisa39 commented on src/constants/types.tsx
Okay yes I can use zod module

2024-07-18 13:31 UTC, swoocn commented on src/services/api.ts
> +    return {message: 'Error fetching pioneer user with ID',}
Okay, I will revert it back.

2024-07-23 12:02 UTC, closed without merging

2024-07-23 12:03 UTC, swoocn commented
This PR is superseded by PR @ [https://github.com/map-of-pi/map-of-pi-frontend-react/pull/121](https://github.com/map-of-pi/map-of-pi-frontend-react/pull/121).