seller item screen created
map-of-pi/map-of-pi-frontend pull request #28
Opened 2024-05-23 07:59 UTC by adisa39

Seller Item UI created with Trust Ometer component for your review

2024-05-24 03:46 UTC, swoocn commented on src/app/[locale]/seller/product/page.tsx
The add-product screen looks nice but isn't a PiFest scope requirement.

2024-05-24 03:52 UTC, swoocn commented on src/app/[locale]/seller/seller-item/page.tsx
Great job on the screen!  Please refer to updated screen requirements @ https://sharing.clickup.com/9015444408/t/h/86byq700x/A7DI9S5MNNJW8YA per UX team.  Thx!

2024-05-24 03:55 UTC, swoocn commented
@adisa39 - The **Buy From Seller** screen looks great!  Please refer to updated screen requirements @ https://sharing.clickup.com/9015444408/t/h/86byq700x/A7DI9S5MNNJW8YA.  The expected screen will now look like ->

![image](https://github.com/map-of-pi/map-of-pi-frontend-react/assets/72060658/b26732a7-a89a-4d31-8b26-34d5b156b974)

2024-05-24 03:56 UTC, swoocn requested changes
New screen requirements @ https://sharing.clickup.com/9015444408/t/h/86byq700x/A7DI9S5MNNJW8YA.

2024-05-24 04:01 UTC, adisa39 commented on src/app/[locale]/seller/seller-item/page.tsx
Alright👍

2024-05-25 15:02 UTC, hollusam approved these changes

2024-05-26 18:32 UTC, swoocn commented
GJ with the adjustments, @adisa39!  
Please see the following notes based off the latest design comments (reference @  https://www.figma.com/design/gSxgy18iMqrs9JorIaznCV/pi_commerce_app_mockup?node-id=1054-3828&t=F8HKgQfnc0YOBEHy-1) ->

![image](https://github.com/map-of-pi/map-of-pi-frontend-react/assets/72060658/5275e89b-79fe-41cc-aba2-e74cc874a63b)

Thanks again!

2024-05-26 21:28 UTC, swoocn commented on src/components/shared/Review/emojipicker.tsx
> +    const despairEmoji: Emoji = { name: "Despair", unicode: "🙂", code: ":despair:", value: 1 };
Can you please weigh the value of Despair to 0?  Thanks!

2024-05-27 13:28 UTC, swoocn commented
@adisa39 - We're almost there!
The UX team has finalized the design per below.  Could you please make the adjustments when you can?  Thanks for being so flexible!

![image](https://github.com/map-of-pi/map-of-pi-frontend-react/assets/72060658/30921ddc-ed1e-4da6-a250-13af124045a5)

A few details to note in the updated screenshot ->
- Only the first letter in each sub-header should be in uppercase.
- Please evenly align and center the emoji rating feature.

2024-06-01 13:12 UTC, swoocn approved these changes

2024-06-01 13:13 UTC, merged